version: '3'
services:
    mysqldb:
        image: mysql:latest
        restart: always
        # env_file:
        #     - ".env"
        # mysql -h localhost -P 8989 --protocol=tcp -u user_name -p
        environment:
            - MYSQL_DATABASE=yii
            - MYSQL_ROOT_PASSWORD=yii
            - MYSQL_USER=yii
            - MYSQL_PASSWORD=yii
        ports:
            - "8989:3306"
        volumes:
            - "./database:/docker-entrypoint-initdb.d"
    php:
        # image: nanoninja/php-fpm:8.1
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./:/var/www/html"
        # command: echo "doc-comp odpalam"
        build:
            context: docker
            dockerfile: ../docker/Dockerfile

    web:
        build:
            context: docker
            dockerfile: ../docker/Dockerfile
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            # - "./etc/ssl:/etc/ssl"
            - "./:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8000:80"
            - "3000:443"
        environment:
            - NGINX_HOST=localhost
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
        external_links:
            - php


volumes:
  php:
  web:
  mysqldb:
